[directives.AcceptEnv]
  comment = [
    "Specifies what environment variables sent by the client",
    "will be copied into the session's environ(7).  See SendEnv",
    "and SetEnv in ssh_config(5) for how to configure the",
    "client.  The TERM environment variable is always accepted",
    "whenever the client requests a pseudo-terminal as it is",
    "required by the protocol.  Variables are specified by name,",
    "which may contain the wildcard characters ‘*’ and ‘?’.",
    "Multiple environment variables may be separated by",
    "whitespace or spread across multiple AcceptEnv directives.",
    "Be warned that some environment variables could be used to",
    "bypass restricted user environments.  For this reason, care",
    "should be taken in the use of this directive.  The default",
    "is not to accept any environment variables.",
  ]
  values = { space_separated = "wildcard" }

[directives.AddressFamily]
  comment = [
    "Specifies which address family should be used by sshd(8).",
    "Valid arguments are any (the default), inet (use IPv4",
    "only), or inet6 (use IPv6 only).",
  ]
  values = { typed = ["any", "inet", "inet6"] }

[directives.AllowAgentForwarding]
  comment = [
    "Specifies whether ssh-agent(1) forwarding is permitted.",
    "The default is yes.  Note that disabling agent forwarding",
    "does not improve security unless users are also denied",
    "shell access, as they can always install their own",
    "forwarders.",
  ]
  values = { typed = ["yes", "no"] }

[directives.AllowGroups]
  comment = [
    "Specifies what environment variables sent by the client",
    "will be copied into the session's environ(7). See SendEnv",
    "and SetEnv in ssh_config(5) for how to configure the client.",
    "The TERM environment variable is always accepted whenever",
    "the client requests a pseudo-terminal as it is required by",
    "the protocol. Variables are specified by name, which may ",
    "contain the wildcard characters ‘*’ and ‘?’. Multiple",
    "environment variables may be separated by whitespace or",
    "spread across multiple AcceptEnv directives. Be warned",
    "that some environment variables could be used to bypass",
    "restricted user environments. For this reason, care should",
    "be taken in the use of this directive. The default is not ",
    "to accept any environment variables."
  ]
  values = { space_separated = "wildcard" }


[directives.Ciphers]
  comment = [
    "Specifies the ciphers allowed.  Multiple ciphers must be",
    "comma-separated.  If the specified list begins with a ‘+’",
    "character, then the specified ciphers will be appended to",
    "the default set instead of replacing them.  If the",
    "specified list begins with a ‘-’ character, then the",
    "specified ciphers (including wildcards) will be removed",
    "from the default set instead of replacing them.  If the",
    "specified list begins with a ‘^’ character, then the",
    "specified ciphers will be placed at the head of the default",
    "set.",
  ]

  values = { modifier = { comma_separated = { typed = [
    "3des-cbc",
    "aes128-cbc",
    "aes192-cbc",
    "aes256-cbc",
    "aes128-ctr",
    "aes192-ctr",
    "aes256-ctr",
    "aes128-gcm@openssh.com",
    "aes256-gcm@openssh.com",
    "chacha20-poly1305@openssh.com",
  ] } } }

[directives.KexAlgorithms]
  comment = [
    "Specifies the available KEX (Key Exchange) algorithms.",
    "Multiple algorithms must be comma-separated.  Alternately",
    "if the specified list begins with a ‘+’ character, then the",
    "specified methods will be appended to the default set",
    "instead of replacing them.  If the specified list begins",
    "with a ‘-’ character, then the specified methods (including",
    "wildcards) will be removed from the default set instead of",
    "replacing them.  If the specified list begins with a ‘^’",
    "character, then the specified methods will be placed at the",
    "head of the default set.",
  ]
  values = { modifier = { comma_separated = { typed = [
    "curve25519-sha256",
    "curve25519-sha256@libssh.org",
    "diffie-hellman-group1-sha1",
    "diffie-hellman-group14-sha12",
    "diffie-hellman-group14-sha256",
    "diffie-hellman-group16-sha512",
    "diffie-hellman-group18-sha512",
    "diffie-hellman-group-exchange-sha1",
    "diffie-hellman-group-exchange-sha256",
    "ecdh-sha2-nistp256",
    "ecdh-sha2-nistp384",
    "ecdh-sha2-nistp521",
    "sntrup761x25519-sha512@openssh.com",
  ] } } }

[directives.AllowTcpForwarding]
  comment = [
    "Specifies whether TCP forwarding is permitted.  The",
    "available options are yes (the default) or all to allow TCP",
    "forwarding, no to prevent all TCP forwarding, local to",
    "allow local (from the perspective of ssh(1)) forwarding",
    "only or remote to allow remote forwarding only.  Note that",
    "disabling TCP forwarding does not improve security unless",
    "users are also denied shell access, as they can always",
    "install their own forwarders.",
  ]
  values = { typed = ["yes", "no", "all", "local", "remote"] }

[directives.AuthenticationMethods]
  values = { space_separated = { comma_separated = { typed = [
    "pubkey",
    "challenge-response",
    "password",
    "keyboard-interactive",
  ]}}}