//! This file has been automatically generated. Any changes made to it will be overwritten upon subsequent runs!
#[allow(unused_imports)]
use crate::Modifier;
#[allow(unused_imports)]
use nom::{
    branch::alt,
    bytes::complete::{tag, tag_no_case, take_until, take_while1},
    character::complete::{alphanumeric1, one_of, space0, space1},
    combinator::{into, map, not, opt, value},
    multi::{many1, separated_list1},
    sequence::{preceded, tuple},
    IResult,
};
#[allow(unused_imports)]
use std::borrow::Cow;

/// Specifies revoked public keys file, or **none** to not use one.
///
/// Keys listed in this file will be refused for public key authentication.
/// Note that if this file is not readable, then public key authentication will be refused for all users.
/// Keys may be specified as a text file, listing one public key per line, or as an OpenSSH Key Revocation List (KRL) as generated by [ssh-keygen(1)](https://man.openbsd.org/ssh-keygen.1).
/// For more information on KRLs, see the KEY REVOCATION LISTS section in [ssh-keygen(1)](https://man.openbsd.org/ssh-keygen.1).
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct RevokedKeys<'a>(Cow<'a, str>);
impl<'a> RevokedKeys<'a> {
    pub fn new(value: &'a str) -> Self {
        Self(value.into())
    }
}
impl<'a> From<&'a str> for RevokedKeys<'a> {
    fn from(value: &'a str) -> Self {
        RevokedKeys(value.into())
    }
}

impl<'a> crate::Parse<'a> for RevokedKeys<'a> {
    type Output = RevokedKeys<'a>;
    fn parse(input: &'a str) -> IResult<&'a str, Self::Output> {
        preceded(
            tag("RevokedKeys"),
            preceded(
                space1,
                map(
                    preceded(space0, take_while1(|c: char| !c.is_whitespace())),
                    RevokedKeys::from,
                ),
            ),
        )(input)
    }
}

impl<'a> From<RevokedKeys<'a>> for crate::Directive<'a> {
    fn from(directive: RevokedKeys<'a>) -> Self {
        crate::directive::Directive::RevokedKeys(directive)
    }
}

